#!/bin/bash
#SBATCH --job-name=hisat2_index
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -c 20
#SBATCH --mem=200G
#SBATCH --partition=general
#SBATCH --qos=general
#SBATCH --mail-type=ALL
#SBATCH --mail-user=username@uconn.edu
#SBATCH -o %x_%j.out
#SBATCH -e %x_%j.err

echo `hostname`
date

#################################################################
# Index the Genome
#################################################################

# load software
module load hisat2/2.2.0

# input/output directories
OUTDIR=~/pilot_evolution/genomes/chm13_dm-hisat2-index
mkdir -p $OUTDIR

GENOME=~/pilot_evolution/genomes/chm13_dm.fa

hisat2-build -p 20 $GENOME $OUTDIR/chm13_dm
